FROM nginx:alpine

# Copia i file compilati del sito (HTML/JS/CSS)
COPY webui/dist /usr/share/nginx/html

# Copia la configurazione custom di Nginx
COPY webui/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80