FROM golang:1.25.1 AS builder
WORKDIR /src/
COPY . .
RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bookworm
EXPOSE 3000
WORKDIR /app/
COPY --from=builder /app/webapi ./

# Change the owner of the /app folder to the user with ID 1000.
# This allows user 1000 to create the .db file inside it.
RUN chown -R 1000:1000 /app
# -----------------------------

CMD ["/app/webapi"]